import Head from "next/head";
import { useRouter } from "next/router";

import Navbar2 from "../Navbar/navbar-2.component";
import Navbar from "../Navbar/navbar.component"

const Header = () => {
    const router = useRouter();
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link
                rel="preload"
                href="http://fonts.cdnfonts.com/css/manrope"
                as="font"
                type="font/manrope"
                crossorigin
                />
                <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"/>
    
            </Head>

            {
                router.pathname == '/news/[slug]' ? (
                    <Navbar2/>
                ) : (
                    <Navbar/>
                )
            }
        </>

      
    );
};

export default Header;